### ISSUE TITLE
Game crash after loading a material edited model (only new _bibo material)

### ISSUE THREAD

**Issue by TheSparkyro** [xivdev/Penumbra#155]
I was trying to update my modlist today and installed the new bibo update (tested with it installed via just textools, just penumbra and installed in both places at once). But any time i tried to update a model to use the new 'bibo' material instead of 'b' or 'd' depending on the mod the game instantly chrashes once that model is loaded ingame (in world, character select, item preview).
Also tried going the other way out of curiosity and found that trying to edit a model already using the new bibo material to something else (b or d) also produced the same effect by instantly crashing when loaded.

Mods getting the material auto assigned by installing via textools worked perfectly with the new material on my PC, but any penumbra based material changes produced crashes instead. 

example change:
![Material updatePNG](https://user-images.githubusercontent.com/18305603/154812473-ac72ef34-72d5-46f0-8cb4-2b2edf83b4b3.PNG)

**Comment by Ottermandias** [comment]
I just pushed an update that should hopefully fix it a few minutes ago.

**Comment by TheSparkyro** [comment]
Still crashing after the update on my end.

**Comment by TheSparkyro** [comment]
Still crashing on model load as of version 0.4.7.6, also tested on an additional computer just in case something was wrong with the install on one of them.
Do let me know if there is any additional information you might require from me.

**Comment by Ottermandias** [comment]
You are trying with a file not previously modified by penumbra each time, yeah?
Can you send me a mdl before and after TexTools conversion?

**Comment by TheSparkyro** [comment]
Yes i have either tried with a new mod altogether or deleted and reimported the same mod (to make sure its not modified).
Not quite sure how i should go about getting the .mdl file if thats the one you wanted. I could provide .ttmp2 files to install one not updated (still using _b material) and one with the right material assigned ( _bibo ).

**Comment by Ottermandias** [comment]
Yeah, do that please.

**Comment by TheSparkyro** [comment]
Links to mods i used for this:
Bibo: https://www.xivmodarchive.com/modid/29029
Moonfire Happi: https://www.xivmodarchive.com/modid/41496

Here are the moonfire happi ttmp2 files one edited and one original model:
https://drive.google.com/file/d/1_voDgYSf54d3iu3VxvzwLLMM5bKc9RQJ/view?usp=sharing

If you want to test for crash on your end this is how i set up on my extra computer to test:
1. Set up a collection with bibo and a bibo mod in penumbra.
2. When loaded ingame the item in the bibo mod should either be invisible or have wrong skin textures.
3. Use the penumbra model edit to change from material 'b' or 'd' to 'bibo'
4. Reload model (item preview or other model loads)
5. Game freezes and then quickly crash.

**Comment by TheSparkyro** [comment]
Interesting discovery, this crash does actually not affect every single item, and the material swap works in some cases.
The moonfire happi i linked can actually swap material without problem. 
All other items i have tried so far on the other hand has crashed.

**Comment by TheSparkyro** [comment]
Made a material swap in textools on an item i know crashes when edited to bibo material.
Etoile longcoat from here: https://www.xivmodarchive.com/modid/39344#info

ttmp2 files:
https://drive.google.com/file/d/1IGRz-XyxshQ2f0Iag4eunGsMrbO5Egwo/view

**Comment by TheSparkyro** [comment]
Issue fixed as of 4.7.7
Great work getting this issue resolved. Must have been frustrating dealing with an issue that initially arrived from sudden swap to longer material layer names.
